- node/main.go
- tikv/client.go
- tikv/errors.go
- tikv/mvcc.go
- tikv/server.go
Prewrite/Commit/Rollback/Get/Scan
> support basic functionality

- .gitignore
- tikv/aggregate.go
- tikv/client.go
- tikv/cop_handler.go
- tikv/executor.go
- tikv/mvcc.go
- tikv/server.go
- tikv/topn.go
It's runnable now.
Most of the code is copied from `mocktikv`.
Need to rename `vendor` under `tidb` to `_vendor` to build.
> support coprocessor request.

- make.sh
- node/main.go
- tikv/analyze.go
- tikv/errors.go
- tikv/mvcc.go
- tikv/server.go
BatchGet, Analyze, ResolveLock, Cleanup, DeleteRange.
> refactor and support more commands

- tikv/analyze.go
- tikv/errors.go
- tikv/mvcc.go
- tikv/region.go
- tikv/resolve_cache.go
- tikv/server.go
- tikv/types.go
- tikv/util.go
The Latest version is separated from the old versions.
The lock is included in the latest version value.
> Change storage model

- make.sh
- node/main.go
- tikv/mvcc.go
> fix GC bug

- tikv/mvcc.go
- tikv/types.go
- tikv/util.go
- tikv/write.go
refactor: 
1. Rename function names
2. Remove unnecessary clock tracking
3. Minimal latch scope
> Tiny refactor

- tikv/mvcc.go
The lock store only supports insert and delete, if there is a same key, insert would fail and panic.
When we meet a duplicate prewrite, we should not write the lock store.
> fix duplicate prewrite request caused panic.

- tikv/mvcc.go
Also rename lockVer to maxSystemTS.
> fix timestamp comparation in KvGet

- lockstore/iterator.go
- lockstore/lockstore.go
- lockstore/lockstore_test.go
- tikv/mvcc.go
- tikv/write.go
LockStore confuses a lot, since rollback key-value is also stored in LockStore.
> rename LockStore to MemStore

- tikv/cop_handler.go
`EncodeType` has been removed.
> fix build with latest tipb

- tikv/mvcc.go
- tikv/types.go
Avoid one DB.Get in Commit operation.
> add old value to lock

- node/main.go
- rowcodec/common.go
- rowcodec/encoder.go
- tikv/mvcc.go
- tikv/region.go
- tikv/server.go
- tikv/util.go
Use a flag to control db sharding. Disable it when work with master tidb-server.
> add a flag to control shard-key feature

- tikv/closure_exec.go
- tikv/cop_handler.go
- tikv/executor.go
- vendor/github.com/pingcap/tidb/util/chunk/chunk.go
implement closure executor for `TopN` operator
> add topn closure executor

- lockstore/arena.go
> fix memory leak in lock store

- tikv/db_reader.go
- tikv/executor.go
- tikv/mvcc.go
- tikv/types.go
- tikv/write.go
So we don't need to read the value from vlog to get the startTS and commitTS.
Prepare for GC.
> move startTS and commitTS from mvccValue to UserMeta.

- go.mod
- go.sum
- tikv/closure_exec.go
- tikv/cop_handler.go
- tikv/executor.go
- tikv/util.go
fix crash when setting shardKey to false.
> fix crash when setting shardKey to false

- tikv/cop_handler_test.go
port the point_get test from [table_scan.rs](https://github.com/tikv/tikv/blob/master/src/coprocessor/dag/executor/table_scan.rs) to cop_handler_test.go in unistore
> port point_get test from table_scan.rs to unistore (#113)

- tikv/raftstore/config.go
- tikv/raftstore/config_test.go
> add raftstore config

- pd/client.go
- tikv/region.go
We will later add more PD features in it.
> move pd client to pd package

- pd/client.go
- tikv/region.go
Replace sizeHint with approximateSize.
> Replace sizeHint with approximateSize

- tikv/closure_exec.go
- tikv/dbreader/db_reader.go
- tikv/mvcc.go
- tikv/server.go
So it can be used outside of 'tikv' package.
> move DBReader to its own package

- go.mod
- tikv/raftstore/keys.go
- tikv/raftstore/peer_storage.go
> [peer_storage.rs] handle raft ready

- tikv/raftstore/peer_storage.go
We will use atomic operations on JobStatus.
> JobStatus: int -> int64

- go.sum
- tikv/raftstore/util.go
- tikv/raftstore/util_test.go
> check region epoch

- tikv/raftstore/engine.go
- tikv/raftstore/msg.go
- tikv/raftstore/peer_storage.go
Add a wrapper for db snapshot and some tiny functions,  they will be used later.
> db snapshot

- tikv/region.go
conversion from pointer to unsafe.Pointer cause memory allocation, change the parent type to unsafe.Pointer to avoid it.
> optimize unsafe.Pointer casting.

- go.mod
- go.sum
- tikv/raftstore/peer.go
Propose with context after raft lib has implemented the feature.
> propose with context

- go.sum
- tikv/raftstore/cmd_resp.go
- tikv/raftstore/cmd_resp_test.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/fsm_test.go
- tikv/raftstore/msg.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/test_util_test.go
- tikv/raftstore/ticker.go
- tikv/raftstore/util.go
The ticker is different from TiKV but does the same work.
> port PeerFsm step 1

- tikv/raftstore/cmd_resp.go
- tikv/raftstore/cmd_resp_test.go
- tikv/raftstore/config.go
- tikv/raftstore/config_test.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/msg.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/peer_storage_test.go
- tikv/raftstore/test_util_test.go
- tikv/raftstore/ticker.go
- tikv/raftstore/util.go
- tikv/raftstore/worker.go
Remove Clone pb struct code.
Remove peerCache.
Remove importSST related code.
> raftstore: simplify code.

- tikv/raftstore/coprocessor.go
- tikv/raftstore/worker.go
> Port splitCheckRun of worker, step 1

- tikv/raftstore/bootstrap.go
- tikv/raftstore/bootstrap_test.go
- tikv/raftstore/cmd_resp.go
- tikv/raftstore/coprocessor.go
- tikv/raftstore/engine.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/peer_storage_test.go
- tikv/raftstore/snap_test.go
- tikv/raftstore/state.go
- tikv/raftstore/test_util_test.go
Also replaced pb type `RaftLocalState` and `RaftApplyState` to simply struct type to reduce clone cost.
> port apply fsm step 3

- tikv/raftstore/coprocessor.go
- tikv/raftstore/worker.go
> Port splitCheckRun of worker, step 2

- pd/client.go
> add more pd client methods

- tikv/raftstore/coprocessor.go
> Port splitCheck and splitCheckObserver implementations, step 1

- go.mod
- tikv/raftstore/coprocessor.go
- tikv/raftstore/worker.go
> Port splitCheck and SplitCheckObserver implementations, step 2

- tikv/errors.go
- tikv/mvcc.go
- tikv/server.go
convert `ErrKeyAlreadyExists` to `kvrpcpb.AlreadyExist`
passed `tidb-test/mysql-test`
> Fix error message

- go.mod
- go.sum
- tikv/closure_exec.go
- tikv/dbreader/db_reader.go
- tikv/executor.go
- tikv/server.go
So we can avoid read vlog for count(*).
> Replace ScanFunc with ScanProcessor

- tikv/mvcc/tikv.go
- tikv/raftstore/bootstrap.go
- tikv/raftstore/bootstrap_test.go
- tikv/raftstore/cmd_resp.go
- tikv/raftstore/engine.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/peer_storage_test.go
- tikv/raftstore/snap.go
- tikv/raftstore/test_util_test.go
Because unistore doesn't have CF, executing write command is complex, the code is not directly ported, need careful review.
> port apply fsm step 4

- tikv/raftstore/coprocessor.go
- tikv/raftstore/worker.go
>  Port splitCheck and SplitCheckObserver implementation, step 4

- tikv/raftstore/peer_storage.go
- tikv/raftstore/worker.go
> Port regionWorker, step 1

- node/main.go
- tikv/mvcc.go
- tikv/mvcc/db_writer.go
- tikv/raftstore/db_writer.go
- tikv/region.go
- tikv/server.go
- tikv/write.go
So we can optionally enable raft.
> introduce DBWriter interface

- tikv/raftstore/engine.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/snap.go
- tikv/raftstore/snap_test.go
- tikv/raftstore/test_util_test.go
- tikv/raftstore/util.go
- tikv/raftstore/worker.go
- tikv/raftstore/worker_test.go
> Port regionWorker, step 2

- lockstore/iterator.go
- lockstore/lockstore.go
- tikv/raftstore/util.go
- tikv/raftstore/worker.go
- tikv/raftstore/worker_test.go
> Port regionWorker, step 3

- tikv/raftstore/fsm_store.go
- tikv/raftstore/raft_client.go
- tikv/raftstore/resolver.go
- tikv/raftstore/snapRunner.go
- tikv/raftstore/transport.go
- tikv/raftstore/worker.go
There are components that need to port:
- resolverRunner
- snapRunner
- raftClient
> port transport

- tikv/raftstore/resolver.go
> port resolver

- tikv/raftstore/config.go
- tikv/raftstore/raft_client.go
> port raft client

- tikv/raftstore/config.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/snapRunner.go
- tikv/raftstore/worker.go
> port snap runner

- tikv/dbreader/db_reader.go
- tikv/raftstore/coprocessor.go
- tikv/raftstore/coprocessor_test.go
- tikv/raftstore/temp_test.go
- tikv/raftstore/worker.go
> Port splitCheck and SplitCheckObserver test.

- tikv/mvcc/tikv.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/db_writer_test.go
- tikv/raftstore/fsm_apply.go
> implement raftWriteBatch

- tikv/mvcc.go
- tikv/mvcc/db_writer.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/msg.go
- tikv/raftstore/pd_runner.go
- tikv/raftstore/peer.go
- tikv/raftstore/worker.go
- tikv/server.go
- tikv/write.go
- Add `kvrpcpb.Context` to NewWriteBatch.
- Change Callback from function to struct type with wait group.
>  implement raftDBWriter.Write

- tikv/cop_handler_test.go
- tikv/raftstore/db_writer_test.go
@coocood PTAL, thanks. There are some issues in `cop_handler_test.go` and `db_writer_test.go` caused by code changes of dependent API. This pr fix this.
> fix bugs in some test caused by code changes.

- go.mod
- pd/client.go
- tikv/raftstore/config.go
- tikv/raftstore/db_writer_test.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/node.go
- tikv/raftstore/peer.go
- tikv/raftstore/snap_manager.go
- tikv/region.go
- port node.rs
- `Bootstrap()` should return response
- update config
- `pdWorker` should create outside of raftstore
- `SnapManager` should send message using `router`
> Port node.rs and other minor changes

- node/main.go
- tikv/region.go
- tikv/server.go
Introduce `RegionManager` interface which supports `GetRegionFromCtx` and `CheckLeader`.
PTAL @coocood
> refactor RegionManager

- go.mod
- go.sum
- node/main.go
- tikv/raftstore/engine.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/peer.go
- tikv/raftstore/read.go
> fix some bugs

- tikv/raftstore/node.go
- tikv/raftstore/server.go
Splitting region like `StandAlongRegionManager`.
> split region at bootstrap

- tikv/mvcc/tikv.go
- tikv/raftstore/fsm_apply.go
- tikv/raftstore/worker.go
> fix some bugs in raftstore

- go.mod
- go.sum
- tikv/raftstore/db_writer.go
- tikv/raftstore/fsm.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/node.go
- tikv/raftstore/peer.go
- tikv/raftstore/read.go
- tikv/raftstore/server.go
- tikv/raftstore/snap_applier.go
- tikv/raftstore/snap_builder.go
- tikv/region.go
- tikv/server.go
> fix bugs in raftstore and server

- tikv/raftstore/snap_applier.go
> fix snapApplier

- node/main.go
- tikv/inner_server.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/server.go
> graceful shutdown

- tikv/dbreader/db_reader.go
> fix inconsistent index problem found during tpcc

- tikv/raftstore/node.go
> fix panic when bootstrap a bootstrapped cluster

- tikv/raftstore/peer_state.go
- tikv/region.go
Benchmark shows it scale better on multi-core 
https://go-review.googlesource.com/c/sync/+/33912
> replace RWMutex and map with sync.Map

- tikv/region.go
The performance benefit may not worth the risk to introduce concurrency bug.
> revert sync.Map in region manager.

- tikv/cop_handler_test.go
- tikv/errors.go
- tikv/mvcc.go
- tikv/mvcc/db_writer.go
- tikv/mvcc/mvcc.go
- tikv/mvcc/tikv.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/engine.go
- tikv/raftstore/fsm_apply.go
- tikv/server.go
- tikv/server_batch.go
- tikv/write.go
- util/lockwaiter/lockwaiter.go
Refactored based on https://github.com/ngaut/unistore/pull/173
> support pessimistic transaction

- go.mod
- go.sum
- tikv/dbreader/db_reader.go
- tikv/raftstore/io_limiter.go
- tikv/raftstore/keys.go
- tikv/raftstore/snap.go
- tikv/raftstore/snap_applier.go
- tikv/raftstore/snap_manager.go
- tikv/raftstore/worker.go
- tikv/region.go
Update badger and use new ingest sst feature to apply snapshot
> use ingest external table to apply snapshot

- tikv/analyze.go
Use DBReader directly instead of tableScanExec and indexScanExec
So tableScanExec and indexScanExec can be removed later.
> refactor analyze executor

- tikv/closure_exec.go
- tikv/cop_handler.go
- tikv/cop_handler_test.go
- tikv/executor.go
test passed on tidb-test/mysql_test except some partition test case.
> closure executor support all DAG

- go.mod
- go.sum
- tikv/mvcc.go
- tikv/mvcc/mvcc.go
- tikv/region.go
- tikv/server.go
- tikv/server_batch.go
Fixes https://github.com/ngaut/unistore/issues/248
- make it work with the latest tidb-server
- avoid region manager deadlock by waitParent in another goroutine.
> support CheckTxnStatus and TxnHeartBeat and fix deadlock

- tikv/raftstore/applier.go
- tikv/raftstore/db_writer_test.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/msg.go
- tikv/raftstore/peer_state.go
- tikv/raftstore/router.go
merge `applyDelegate` and `applyFsm` to a single type `applier`.
> refine the code about apply 

- unistore-server/main.go
It’s the same as TiKV
Jepsen uses it to check if the server is up.
> support http status API

- pd/client.go
> prepend scheme before pd addr

- pd/client.go
> fix pd request retry after timeout

- pd/client.go
- tikv/raftstore/node.go
- tikv/raftstore/pd_runner.go
Add leader peer as return value for `GetRegion`  and `GetRegionByID`
> pdclient: return leader from GetRegion api

- unistore-server/main.go
So we can use one config file for multiple node, set store address for different nodes, set pd address dynamically.
> add command line argument for pd address and store address

- tikv/raftstore/applier.go
Fixes https://github.com/ngaut/unistore/issues/273
> fix apply destroy panic

- tikv/region.go
Fixes https://github.com/ngaut/unistore/issues/276 https://github.com/ngaut/unistore/issues/271
> handle region event in a dedicated goroutine

- tikv/raftstore/db_writer_test.go
Reopen the db_write_test.go and make the "TestRaftWriteBatch_PrewriteAndCommit" case work
> [unit-test]:fix db write test

- tikv/mvcc_test.go
Add some common test transaction test utilities like in tikv, make it more convenient to port tikv transaction-related tests, tikv package now coverage now 21.9%
> [txn] Wrap some common test utility like tikv

- config/config.go
- tikv/raftstore/config.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/worker.go
- unistore-server/main.go
#300 
Add keys split checker and related config fields
> [RaftStore] Add keys split checker

- tikv/cop_handler_test.go
The `kvproto` and `tipb`  changed and leads to unit test fail compliling, fix this so that the tikv package unit test will run
> [coprocessor] Fix cop test

- tikv/raftstore/applier.go
The `Op_Lock` key  prewrite should record the old value, or the `execCommit` will not treat it as old key and commit info is incorrect, jepsen tests will fail and report invalid, errors like
```
jepsen worker 2-n3 - jepsen.core Process 5862 crashed
java.lang.NullPointerException: null
at clojure.lang.Numbers.ops(Numbers.java:1068) ~[clojure-1.10.0.jar:na]
at clojure.lang.Numbers.add(Numbers.java:153) ~[clojure-1.10.0.jar:na]
at tidb.bank.BankClient$fn__3131$fn__3132$fn__3133$fn__3134.invoke(bank.clj:68) ~[classes/:na]
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799) ~[classes/:na]
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769) ~[classes/:na]
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782) ~[classes/:na]
at …
```
> [raftStore] fix op_lock prewrite

- tikv/cop_handler_test.go
- tikv/dbreader/db_reader.go
- tikv/mvcc_test.go
~~1. Add item length check for `dbReader.get` (item.Value could be non nil zero length slice)~~
2. Port some basic txn tests from tikv(current  tikv package coverage 22.1 %)
3. Refactor some test functions and make them clean
> refactor test util, port txn tests from tikv

- config/config-template.toml
- config/config.go
- unistore-server/main.go
Add configurations needed to integrate `unistore` into `tidb-ansible`
> add config needed by ansible

- go.mod
- go.sum
- unistore-server/main.go
> update badger version to support close not compact

- tikv/raftstore/applier.go
- tikv/raftstore/peer_worker.go
There are two workers: raftWorker and applyWorker.
The raftWorker sends apply task message to applyWorker and the applyWorker sends apply result message to raftWorker.
When the raftWorker channel is full, the two workers block each other, the server hang forever.
Make the applyWorker send apply result messages to a dedicated channel to avoid channel full.
> fix server hang due to raft channel is full

- tikv/server_batch.go
Make it work with the latest tidb-server master
> support BatchCommandsRequest_Request_Empty

- tikv/errors.go
- tikv/mvcc.go
- tikv/mvcc_test.go
- tikv/server.go
Port https://github.com/tikv/tikv/pull/6353
> support commit pessimistic lock

- go.sum
- tikv/errors.go
- tikv/mvcc.go
- tikv/mvcc_test.go
1. fix some case logic
2. cherry-pick op `check not exist` processing logic
> txn: fix some cases and add check exists logic

- tikv/mvcc.go
- tikv/mvcc_test.go
- tikv/server.go
Fixes https://github.com/ngaut/unistore/issues/358
> Fix GC and implement Green GC methods

- tikv/mvcc.go
- tikv/mvcc_test.go
Skip the conflict check for force pessimistic lock
> txn: skip check for force lock

- tikv/mvcc.go
- tikv/mvcc_test.go
A given lock need to check the start TS.
> fix resolve lock bug again

- tikv/raftstore/engine.go
- unistore-server/main.go
Reduce the compaction cost for raft DB
> implement Guard for raft DB

- go.mod
- go.sum
Fixes https://github.com/ngaut/unistore/issues/362
> update badger version for replay log bug fix

- tikv/mvcc.go
- tikv/server.go
- util/lockwaiter/lockwaiter.go
Complete the force lock logic, some tests are in [tidb-change](https://github.com/pingcap/tidb/pull/16031)
> txn: complete force lock logic

- tikv/region.go
- tikv/write.go
- unistore-server/main.go
> fix stand-alone region manager

- tikv/closure_exec.go
- tikv/cop_handler_test.go
- tikv/mock_region.go
- tikv/mvcc.go
- tikv/mvcc_test.go
- tikv/server.go
KvScan should keep scanning even if it meets lock.
> fix KvScan that returns early when meet lock.

- tikv/mvcc.go
- tikv/region.go
Fixes https://github.com/pingcap/tidb/pull/17397
> fix unit test for MVCCGetInfo

- tikv/dbreader/db_reader.go
To support move coprocessor to tidb repo
> expose DBReader startKey and endKey

- go.mod
- go.sum
- tikv/mvcc.go
- tikv/mvcc_test.go
- tikv/raftstore/snap_builder.go
SampleStep is used for fast analyze to collect sampled key value pairs.
> support sample step option in KvScanRequest

- go.mod
- go.sum
Update badger to include https://github.com/pingcap/badger/pull/202
> update badger for better windows support

- go.mod
- go.sum
- tikv/mvcc_test.go
- tikv/raftstore/applier.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
Signed-off-by: linning <linningde25@gmail.com>
> update kvproto dependencies

- go.mod
- go.sum
- pd/client.go
- tikv/mock_region.go
This PR is the stage 1 of https://github.com/pingcap/tidb/issues/19306 , in order to upgrade the PD dependency of tidb related repo.
**Note**: After merging this PR, it will temporarily be unable to compile.
> update pd dependencies

- go.mod
- go.sum
- pd/client.go
- tikv/mock_region.go
This PR is the stage 3 of https://github.com/pingcap/tidb/issues/19306 , in order to upgrade the PD dependency of tidb related repo.
> update pd and tidb dependencies

- tikv/mvcc.go
The scan processor needs to consider the `limit` input parameter for the data scan and lock scan(thanks for @bobotu for reminding about this key point). 
Currently, the lock scan may return more keys than expected by the input limit parameter, if there are keys being committed in the same range.
Try to add the limit parameter into `collectRangeLock` and the `validPairs` collecting logic so there will not be more keys than expected.
It's easy to reproduce the scan_test failure on TiDB skipping commit specific secondary keys, like this:
```
skip these two keys doing commit, log in unistore
[WARN] [mvcc.go:865] ["[for debug] skip commit key"] [startTS=418999667188039680] [key=7480000000000000015f7280000000000002f5]
[WARN] [mvcc.go:865] ["[for debug] skip commit key"] …
```
> txn: fix scan lock process

- go.mod1
- go.sum1
- tikv/mvcc.go
- tikv/mvcc/mvcc.go
- tikv/server.go
- tikv/write.go
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
> Add support for single region 1pc

- tikv/mock_region.go
- tikv/region.go
- tikv/server.go
migrate tiflash mock test from mocktikv to unistore
> migrate tiflash mock test from mocktikv to unistore

- go.mod1
- go.sum1
- tikv/mvcc.go
Implement https://github.com/pingcap/kvproto/pull/705 and pick https://github.com/tikv/tikv/pull/9272 on unistore.
> txn: change check txn status logic

- tikv/mock_region.go
- tikv/server.go
As the mpp test increases, there are tasks running on same store. We must add lock to avoid data race.
> add lock gaurd for mpp task loading and storing to avoid data race

- tikv/server.go
we could run mpp task directly instead of converting it to cop requests.
> tikv/server: refine mpp code without mess

- tikv/server.go
get the dbreader before the req ctx finishes.
> fix data race

- go.mod1
- go.sum1
- tikv/server.go
Signed-off-by: yisaer <disxiaofei@163.com>
This PR is going to update kvproto to the latest version. Currently, it blocks the TiDB to use the latest kvproto.
> *: update kvproto to the latest version

- go.mod
- go.sum
> replace raft mod to hslam/raft-1

- cmd/unistore-server/main.go
- go.mod
- go.sum
- server/server.go
https://github.com/ngaut/unistore/issues/460
* To view statsviz, open your browser at http://status-addr/debug/statsviz
* Or to view shard db info, open http://status-addr/debug/db
> introduce statsviz and register a debug HTTP handler

- sdb/compaction.go
- sdb/flush.go
- sdb/options.go
- sdb/shard.go
- server/server.go
- tikv/mvcc.go
- reduce the L0 table size by half.
- fix compaction filter for LockCF.
> add ReadCommitted property tor LockCF

- sdb/compaction.go
- sdb/db.go
- sdb/ingest.go
- sdb/split.go
fixed https://github.com/ngaut/unistore/issues/466
> fix inconsistent size and adjust debug handler

- sdb/compaction.go
fix https://github.com/ngaut/unistore/issues/470
> fix l0 deletions during compaction

- sdb/compaction.go
- sdb/db.go
- sdb/flush.go
- sdb/ingest.go
- sdb/iterator.go
- sdb/shard.go
- sdb/split.go
- sdb/table/concat_iterator.go
- sdb/table/memtable/skl.go
- sdb/table/memtable/skl_test.go
- sdb/table/memtable/table.go
- sdb/table/memtable/table_test.go
- sdb/table/merge_iterator.go
- sdb/table/merge_iterator_test.go
- sdb/table/sstable/iterator.go
- sdb/table/sstable/l0table.go
- sdb/table/sstable/table.go
- sdb/table/sstable/table_test.go
- sdb/table/table.go
- tikv/dbreader/db_reader.go
- tikv/mvcc.go
- tikv/raftstore/applier.go
- tikv/raftstore/engine.go
> replace y.Key with []byte

- sdb/cache/cache.go
- sdb/cache/cache_test.go
- sdb/cache/policy.go
- sdb/cache/policy_test.go
- sdb/cache/ring.go
- sdb/cache/ring_test.go
- sdb/cache/store.go
- sdb/cache/stress_test.go
- sdb/table/sstable/table.go
- sdb/table/sstable/table_file.go
Fixes https://github.com/ngaut/unistore/issues/474
> update cache key from uint64 to struct{ID uint64,  Offset uint32}

- config/config.go
- sdb/compaction.go
- sdb/db.go
- sdb/db_test.go
- sdb/ingest.go
- sdb/options.go
- sdb/shard.go
- sdb/split.go
- sdb/table/memtable/arena.go
- sdb/table/memtable/skl.go
- sdb/table/memtable/table.go
- sdb/write.go
- server/server.go
- tikv/raftstore/applier.go
- tikv/raftstore/engine.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/raftlog/custom.go
- tikv/raftstore/recover.go
- tikv/raftstore/test_util_test.go
- tikv/raftstore/worker.go
Fixes https://github.com/ngaut/unistore/issues/482
> support dynamic mem-table size

- sdb/db.go
- sdb/flush.go
- sdb/manifest.go
- sdb/shard.go
- sdb/split.go
- sdb/table/memtable/table.go
- sdb/write.go
- tikv/raftstore/applier.go
- tikv/raftstore/engine.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
- TriggerFlush only flush the not flushed mem-tables.
- write to db before apply each raft log.
> partial fix mem-table inconsistent issue.

- sdb/db.go
- sdb/shard.go
- sdb/split.go
- sdb/write.go
- tikv/raftstore/applier.go
- tikv/raftstore/bootstrap_test.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/engine.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/peer_worker.go
- tikv/raftstore/recover.go
Fixes https://github.com/ngaut/unistore/issues/497
> directly write DB in apply thread

- cmd/unistore-server/main.go
- sdb/db.go
- sdb/flush.go
- sdb/shard.go
- sdb/split.go
- sdb/table/memtable/table.go
- sdb/write.go
- tikv/raftstore/applier.go
- tikv/raftstore/raft_client.go
Resolve https://github.com/ngaut/unistore/issues/482
> support dynamic max mem-table size

- sdb/table/sstable/builder.go
Fixes https://github.com/ngaut/unistore/issues/507
> fix data corruption bug

- sdb/compaction.go
Fixes https://github.com/ngaut/unistore/issues/510
Should update the bottom level, then top level, or in a tiny time window iterator may fail to read data.
> fix compaction bug

- sdb/compaction.go
- sdb/db_test.go
- sdb/manifest.go
- sdb/split.go
- tikv/dbreader/db_reader.go
- tikv/raftstore/bootstrap.go
- tikv/server.go
shard is split before region, it's possible regionManager check pass, but shard version not match.
> check shard version when handle request.

- tikv/raftstore/fsm_store.go
fixed
```
panic: [region 21] 23 region 21:0 unexpected raft log index: lastIndex 0 < appliedIndex 5
goroutine 116 [running]:
github.com/ngaut/unistore/tikv/raftstore.NewPeerStorage(0xc00004ec80, 0xc00050a000, 0xc0000da4e0, 0x17, 0xc0000f4080, 0xe, 0xe, 0x41401c5, 0x66b1d60)
/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/peer_storage.go:247 +0x7ff
github.com/ngaut/unistore/tikv/raftstore.NewPeer(0xc, 0xc000274d20, 0xc00004ec80, 0xc00050a000, 0xc0000da4e0, 0xc014950040, 0x2, 0x0, 0x0)
/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/peer.go:305 +0x185
github.com/ngaut/unistore/tikv/raftstore.replicatePeerFsm(0xc, 0xc000274d20, 0xc0000da4e0, 0xc00004ec80, 0x15, 0xc000490048, 0x12, 0x18, 0xc000490060, 0x12, ...) …
```
> fix a panic when a raft log index is unexpected

- sdb/epoch/manager.go
- tikv/dbreader/db_reader.go
Fixes https://github.com/ngaut/unistore/issues/517 which is introduced in https://github.com/ngaut/unistore/pull/513
> fix resource leak

- sdb/compaction.go
There are some empty sst files. 
Fixed this issue.
> avoid creating empty sst files

- tikv/server.go
Avoid https://github.com/ngaut/unistore/issues/487
> do not compress raft db

- sdb/db.go
- sdb/manifest.go
- sdb/shard.go
Fixes https://github.com/ngaut/unistore/issues/514
> assign shard commitTS on loading

- sdb/manifest.go
Fixes https://github.com/ngaut/unistore/issues/522
Two conflicting compactions generated by different peers don't have the same created table ID but have the same delete table ID.
> use delete ID instead of create ID to check conflict compaction

- tikv/raftstore/engine.go
reduce the raft DB compaction pressure
> fix raft guard prefix

- sdb/db.go
- sdb/shard.go
- sdb/table/memtable/skl.go
- sdb/table/memtable/skl_test.go
- sdb/table/memtable/table.go
> use GetWithHint for mem-table

- Makefile
- cmd/compaction-server/main.go
- config/config.go
- pd/client.go
- raftengine/iterator.go
- s3util/s3util.go
- sdb/compaction.go
- sdb/compaction/client.go
- sdb/compaction/compaction.go
- sdb/compaction/server.go
- sdb/db.go
- sdb/flush.go
- sdb/ingest.go
- sdb/iterator.go
- sdb/options.go
- sdb/shard.go
- sdb/split.go
- sdb/table/memtable/skl_test.go
- sdb/table/sstable/builder.go
- sdb/table/sstable/l0table.go
- sdb/table/sstable/table_test.go
- sdb/table/table.go
- sdb/write.go
- tikv/mvcc.go
- tikv/server.go
Address issue https://github.com/ngaut/unistore/issues/524
> refine remote compaction

- tikv/mvcc.go
- tikv/raftstore/applier.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/recover.go
Address https://github.com/ngaut/unistore/issues/542
> reduce raft log size by not storing lock value in commit

- config/config.go
- tikv/raftstore/applier.go
- tikv/raftstore/config.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/msg.go
- tikv/raftstore/peer_worker.go
- tikv/server.go
eliminate the single thread bottleneck
address https://github.com/ngaut/unistore/issues/536
> optimize applier

- sdb/compaction.go
- sdb/compaction/compaction.go
- sdb/db.go
- sdb/ingest.go
- sdb/iterator.go
- sdb/options.go
- sdb/shard.go
- sdb/split.go
- sdb/table/sstable/l0table.go
- tikv/raftstore/applier.go
- tikv/server.go
avoid move down for lock CF, reduce lock CF size.
> make max level for each CF configurable.

- cmd/compaction-server/main.go
- engine/compaction.go
- engine/compaction/client.go
- engine/compaction/compaction.go
- engine/compaction/server.go
- engine/engine.go
- engine/flush.go
- engine/options.go
- engine/split.go
- pd/client.go
- tikv/mvcc.go
- tikv/server.go
pre-allocate IDs and include them in the compaction request.
So compaction server do not need to connect to PD.
> compaction server do not depends on PD

- raftengine/engine.go
- raftengine/engine_test.go
- raftengine/iterator.go
- raftengine/load.go
- raftengine/worker.go
- raftengine/writer.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/peer_worker.go
- reorder the raft messages
- avoiid marshal/unmarshal eraftpb.Entry for raft engine.
> optimize raft worker

- tikv/raftstore/applier.go
Fix assertion failure when restart recover.
> fix assertion failure by handle duplicated commit.

- raft/raft.go
- tikv/raftstore/peer.go
change the hex peer id to region id in the log message
> make log message in raft package readable.

- raft/log.go
- raft/log_unstable.go
- raft/node.go
- raft/raft.go
- raft/rawnode.go
- raft/storage.go
- raft/util.go
- raftengine/engine.go
- tikv/raftstore/applier.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_storage.go
- tikv/raftstore/recover.go
> use pointer type for eraftpb.Entry

- cmd/unistore-server/main.go
TiDB use health API to check liveness
> register health server

- tikv/raftstore/db_writer.go
- tikv/raftstore/msg.go
- tikv/raftstore/node.go
- tikv/raftstore/read.go
- tikv/raftstore/router.go
- tikv/raftstore/worker.go
Prepare for future optimization
> refactor Callback to use channel instead of wait group.

- tikv/mvcc.go
- tikv/mvcc/engine_writer.go
- tikv/raftstore/db_writer.go
- tikv/raftstore/fsm_peer.go
- tikv/raftstore/fsm_store.go
- tikv/raftstore/msg.go
- tikv/raftstore/peer.go
- tikv/raftstore/read.go
- tikv/raftstore/router.go
- tikv/raftstore/worker.go
Can only tolerate region split, amend logic is not implemented yet.
> support pipelined pessimistic lock

- tikv/raftstore/fsm_peer.go
- tikv/raftstore/peer.go
- tikv/raftstore/peer_worker.go
> schedule apply before raft state persist

- tikv/raftstore/fsm_peer.go
- tikv/raftstore/peer_storage.go
The entry is already cached in the raft engine
> remove entry cache in PeerStorage

- tikv/mvcc.go
When use pipelined pessimistic lock, if a node is kill, it's possible that a pessimistic lock lost,
If there is no conflict, we can proceed the transaction instead of return error
> amend pessimistic lock not found error to reduce failure rate

- raftengine/engine.go
- raftengine/engine_test.go
- raftengine/worker.go
- tikv/raftstore/peer_storage.go
Prepare for implementing multiple raft worker.
> make raft engine thread-safe
