tikv/mvcc.go, tikv/util.go
Use ValidForPrefix avoids conflict.
And add message 'try again later' will make the error retryable in TiDB.
=> fix check prewrite conflict

tikv/cop_handler.go, tikv/executor.go, tikv/mvcc.go, tikv/region.go, tikv/server.go
The `txnKeysMap` is only kept in memory, it can be lost.
So when a request meets a lock, we add it to the `txnKeysMap`, the lock will be able to resolve later.
=> fix the lock unresolvable bug.

tikv/analyze.go, tikv/mvcc.go, tikv/region.go, tikv/types.go
The key in the database is encoded in case appending timestamp at the end may change the order of the key.
But as long as the key is encoded by TiDB, appending timestamp doesn't change the order.
So this PR change to use key directly without extra encoding.
Save some disk space and key comparing cost and simplify the logic.
=> remove key encoding

tikv/mvcc.go
Fix the bug that prewrite keeps retrying.
=> return ErrLocked instead of ErrRetryable in Prewrite

lockstore/arena.go, lockstore/iterator.go, lockstore/lockstore.go, lockstore/lockstore_test.go
A in-memory lock-free data-structure to store lock.
- allows single writer and multiple readers without lock.
- memory can be reused after all the entries in a block are deleted.
=> introduce lockstore

tikv/region.go
RUnlock and RLock might cost more then a memory allocation, let's keep
things simple
=> kv: tiny clean up

tikv/region.go
We don't need to inherent txn keys from parent, we can add them when client encounter it.
=> avoid holding txnKeysMu for long time

tikv/mvcc.go, tikv/types.go, tikv/write.go
1. Fix `Cleanup` mistakenly write the batch to DB instead of lock store and use separate write batch type for Lock and DB to prevent error like this.
2. `Rollback` function should read all keys in lock store before read DB.
3. Fix delete key do actual delete instead of write tombstone.
=> fix bugs found in high conflicting concurrent transaction workload.

tikv/region.go, tikv/server.go
After `WaitGroup.Wait` is called, another call on `Add` will panic, so call `Add` in the Lock to prevent this.
=> fix WaitGroup

tikv/write.go
In TPCC benchmark, the number of rollback keys in one minute is very large, up to hundreds of thousands, It increases max latency a lot.
Split the rollbackGC batch into small batches to avoid high latency.
Although it doesn't improve the throughput.
=> split rollbackGC batch

node/main.go
Add max-procs in configuration to make it easy to control the CPU usage.
PTAL @ngaut @coocood
=> config: add max-procs to control the cpu usage

tikv/aggregate.go, tikv/cop_handler.go, tikv/db_reader.go, tikv/executor.go, tikv/types.go
Implement `nextChunk` to coprocessor executors.
`TopN` and `HashAgg` are not supported yet.
`StreamAgg` only supports `count`.
=> support chunk execution

tikv/aggregate.go, tikv/closure_exec.go, tikv/cop_handler.go, tikv/db_reader.go, tikv/executor.go
And remove partially implemented chunk execution framework code.
Now `tableScan` `indexScan` `limit` `selection` is supported along with `count` aggregation.
mysql_test is passed.
=> support more executors in closure executor

rowcodec/common.go, rowcodec/decoder.go, rowcodec/encoder.go, rowcodec/rowcodec_test.go, tikv/closure_exec.go, tikv/cop_handler.go, tikv/executor.go, tikv/mvcc.go, tikv/server.go
- The old row is converted to the new format in `Prewrite`.
- The new row is converted to the old format if closure executor is not supported for Coprocessor request.
- The new row is converted to the old format in `Scan`, `Get` and `BatchGet`.
=> support the new row format

rowcodec/common.go, rowcodec/decoder.go, rowcodec/encoder.go, rowcodec/rowcodec_test.go, tikv/closure_exec.go, tikv/cop_handler.go, tikv/executor.go, tikv/mvcc.go, tikv/server.go
Benchmark result for 3 column row (int, string, float):
Encode:
10000000	       114 ns/op	       0 B/op	       0 allocs/op
EncodeFromOldRow:
10000000	       257 ns/op	       0 B/op	       0 allocs/op
Decode:
20000000	        65.9 ns/op	       0 B/op	       0 allocs/op
The `EncodeFromOldRow` is currently used, it first decodes from an old row, then encodes to a new row. When we encode row in TiDB, `Encode` will be used.
=> optimize and refactor encoding and add benchmark

tikv/region.go
If shard-key is not enabled, we cannot use multiple DB to separate index and row.
=> fix getDBIdx

go.mod, go.sum, rocksdb/block_based_table_builder.go, rocksdb/block_builder.go, rocksdb/compression.go, rocksdb/filter_builder.go, rocksdb/options.go, rocksdb/props_block_builder.go, rocksdb/slice_transform.go, rocksdb/sst_file_writer.go, rocksdb/types.go, rocksdb/utils.go
I have checked some sst files, which generated by this SstFileWriter with different table size and compression algorithm, using RocksDB's sst check tools and `IngestExternalFiles`.   
This writer simplified many options in RocksDB, which doesn't use by TiKV. We can add them back if need.
I can port some unit tests later.
The first step of #107 😁
=> port SstFileWriter from RocksDB

tikv/raftstore/entry.go, tikv/raftstore/peer_storage.go, tikv/raftstore/peer_storage_test.go, tikv/raftstore/test_util_test.go
entries are all struct type slice in etcd, so we better use struct slice as well.
=> raftstore: use struct instead of pointer type for entry slice.

tikv/mvcc.go, tikv/server_batch.go, tikv/write.go
I recently did a microbenchmark for the two approaches of batching, the difference is very small.
Changing mutex to channel can simplify the code, easier to understand.
=> refactor writeDBWorker and server batch to use channel instead of mutex.

go.mod, go.sum, tikv/raftstore/entry.go, tikv/raftstore/msg.go, tikv/raftstore/peer_storage.go, tikv/raftstore/peer_storage_test.go, tikv/raftstore/snap.go, tikv/raftstore/test_util_test.go
Etcd use its own proto file, there are some conflicts with kvproto/eraftpb.
=> remove etcd/raft dependency

go.mod, go.sum
After added go.mod in badger, use `go get -u` to update the badger version stopped working.
So I use replace to define badger version.
=> update go.mod to use latest badger

tikv/raftstore/fsm.go, tikv/raftstore/fsm_apply.go, tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/fsm_test.go, tikv/raftstore/msg.go, tikv/raftstore/peer.go, tikv/raftstore/peer_storage.go, tikv/raftstore/snap_manager.go, tikv/raftstore/ticker.go
Refactor `Msg` to use `interface` instead of multiple fields.
Since the struct is small, only 32 bytes, we can use value instead of pointer.
Move some code from peer to fsm_apply and fsm_store.
=> port PeerFsm step 2

node/main.go
TiDB use 16 connections for each kv store (maybe it's not wise choosen) and http2 flow control seems to be useless, so int TiDB, dynamic window is disabled
https://github.com/pingcap/tidb/blob/461512b8273a7b64580cd96e34c8e2d7983b5e62/store/tikv/client.go#L249
https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go#L210
but unistore keep use window update frame, from TiDB scheduler pprof:
unionstore keep send updateWindow frame to TiDB, so this PR try to disable it in unistore too
and do some sysbench point-get test:
before:
```
sysbench --config-file=tidb-config oltp_point_select --tables=32 --threads=32 --table-size=100000 run
[ 5s ] thds: 32 tps: 54212.80 qps: 54212.80 (r/w/o: 54212.80/0.00/0.00) lat (ms,95%): 1.01 err/s: 0.00 reconn/s: 0.00
[ 10s ] thds: 32 tps: …
```
=> disable grpc window update

tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/msg.go, tikv/raftstore/node.go, tikv/raftstore/peer.go, tikv/raftstore/server.go
With these callbacks, we can maintain something like `regionCtx` and `leaderChecker` outside raftstore.
PTAL @coocood
=> add some peer event callback

tikv/raftstore/fsm_apply.go
The `execCompactLog` doesn't update `aCtx.execCtx.applyState.truncatedIndex`, so `onRaftGCLogTick` will try to compact log at compacted index 😂
PTAL @coocood
=> fix panic in onRaftGCLogTick

tikv/raftstore/engine.go, tikv/raftstore/fsm_apply.go, tikv/raftstore/keys.go, tikv/raftstore/peer_storage.go, tikv/raftstore/snap.go, tikv/raftstore/snap_builder.go, tikv/raftstore/snap_manager.go
1. Introduce the undo log to lockstore.
2. During snapshot use the same `Txn` to load `ApplyState`, `RegionState` and normal database entries.
PTAL @coocood
=> use undo log to keep lock store snapshot consistent

tikv/dbreader/db_reader.go, tikv/mvcc.go, tikv/raftstore/engine.go, tikv/raftstore/fsm_apply.go, tikv/raftstore/read.go
Fix: 
* The `getOld` and `checkPrewrite` ignore the deleted entry, so they may return an incorrect old version or allow conflicted write.
* Prewrite of `LockKey` will delete the current value. 😂
=> fix mvcc and raft apply

tikv/region.go
Fix bugs in `StandAlongRegionManager` introduced by #209
PTAL @ngaut @coocood
=> add missing value in regionCtx.unmarshal

tikv/raftstore/engine.go, tikv/raftstore/fsm_apply.go, tikv/raftstore/peer_state.go, tikv/raftstore/peer_storage.go, tikv/raftstore/restore.go, tikv/raftstore/worker.go
The new way to generate a consistent snapshot:
Save `redoIdx` on the peer's `applyFsm` at the beginning of the apply batch, if there is a Snapshot request, pass it all the way to `newRegionSnapshot`.
In `newRegionSnapshot`:
1. Get the region start key and end key.
2. Iterate the lockStore to generate a new lockStore for the snapshot.
3. Begin a transaction for the snapshot.
4. Get the region info again to make sure the start key and end key didn't change.
5. restore the raft log between `redoIdx` and `appliedIdx` to snapshot lockstore.
=> replace undo log with redo raft log

tikv/raftstore/coprocessor.go, tikv/raftstore/coprocessor_test.go
-  Use non-encoded startKey and endKey to seek the last key of a region.
- `leftKey` or `rightKey` in `isSameTable` may have length equal to `tablecodec.TableSplitKeyLen`
=> fix tableSplitChecker

rowcodec/common.go, rowcodec/encoder.go
Current union store encodes row data as new row-format:
https://github.com/pingcap/tidb/blob/master/docs/design/2018-07-19-row-format.md
and it changes int/uint encoding:
>For integer values, we store {byte, uint16, uint32, uint64} instead of varint for fast decoding. The type can be inferred by the column value size. The string value is stored as it is. Other types are encoded in the old way without the first type flag byte.
this introduces incompatibility problem if encode value need be used in the query.
for example this script:
```
drop table if exists t1;
create table t1(a time);
insert into t1 values (1), (2), (3);
analyze table t1;
explain select * from t1 where a = 1;
```
explain can not get an accurate count for condition `a=1`
value `1` be encoded as int and `RowToOldRow` as …
=> rowcodec: encode row int/uint as varint/varuint when back to old row

rowcodec/encoder.go
when `r.large == true`,  `colIDs` will in `r.colIDs32` and `RowToOldRow` will return empty result now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ngaut/unistore/241)
=> rowcodec: fix bug in `RowToOldRow` when row is large

util/lockwaiter/lockwaiter.go
The lock waiter manager `Cleanup`  method should use `LockTS` to get the correspond waiting queue
=> fix waiter cleanup

tikv/deadlock.go, tikv/detector.go, tikv/detector_test.go, tikv/errors.go, tikv/mvcc.go, tikv/raftstore/fsm_peer.go, tikv/raftstore/peer.go, tikv/region.go, tikv/server.go, unistore-server/main.go, util/lockwaiter/lockwaiter.go, util/lockwaiter/lockwaiter_test.go
Issue #257 
two related changes could be reviewed separately #269 #270 
Support distributed deadlock detection
- 1. Implement `deadlock` proto related RPC server interface
- 2. Wrap former `detector`  into new `DeadLockDetector`, add role to this new detector, and process requests based on current role(leader/follower)
- 3. Add `detectConn` and `detectClient` to do stream `send` and `recv` [this wrapping removed]
- 4. Add code path to process first region role change callback named `OnRoleChange`
- 5. Add recycling utility for detector wait map
- 6. Move the detector source code and test case from the dependent tidb package to local `tikv.detector.go` , and add some extra utilities.
- 7. Refactor lock waiter manager, remove the queue mutex
The storage engine still has some problems #267 …
=> support distributed dead lock detection

Makefile, tikv/cop_handler_test.go, tikv/raftstore/bootstrap_test.go, tikv/raftstore/db_writer_test.go, tikv/raftstore/peer_storage_test.go, tikv/raftstore/snap_test.go, tikv/raftstore/test_util_test.go, tikv/raftstore/worker_test.go
Make unit test work again
Add `make test` command in Makefile to run all the unit-test cases, resolve some incompatibilities.
Mark some unstable or fail cases for future refactoring.
current `make test` output
```
make test
Running tests in native mode.
?   	github.com/ngaut/unistore/config	[no test files]
ok  	github.com/ngaut/unistore/lockstore	10.660s	coverage: 72.4% of statements
?   	github.com/ngaut/unistore/metrics	[no test files]
?   	github.com/ngaut/unistore/pd	[no test files]
ok  	github.com/ngaut/unistore/rocksdb	2.101s	coverage: 81.6% of statements
ok  	github.com/ngaut/unistore/rowcodec	0.007s	coverage: 42.8% of statements
ok  	github.com/ngaut/unistore/tikv	0.025s	coverage: 9.7% of statements
?   	github.com/ngaut/unistore/tikv/dbreader	[no test files]
? …
```
=> Makefile: add make test

tikv/cop_handler_test.go, tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/peer.go, tikv/raftstore/peer_storage.go, tikv/raftstore/peer_storage_test.go, tikv/raftstore/test_util_test.go
- Only pass necessary parameter instead of the whole PollContext to Peer, so we can infer what a method gonna do.
- remove the unused SyncLog state
=> tiny refactor on raftstore

tikv/deadlock.go, tikv/region.go, unistore-server/main.go
* Close grpc connection when rebuild stream, otherwise the leaked socket will finally result in `too many open files` error.
* Set role when server starts in stand-alone mode.
* Report leader peer to PD when server start.
PTAL @coocood @cfzjywxk
=> fix dead lock detection for stand alone mode

tikv/raftstore/worker.go, tikv/raftstore/worker_test.go
- The `handlePendingApplies` processes apply tasks, which comes in request order in `pendingApplies` array, the successful task should be removed from the pending tasks array, otherwise, redundant processing  leads to `badger` ingestion error like `keys of external tables has overlap` 
- `TestPendingApplies` test case is fixed to make it compatible with the current interfaces
TODO, maybe we need to refactor more on the `handlePendingApplies` error processing path, and some more test cases needed to be added to verify error processing is ok(like reentrancy), to avoid breaking the data consistency
=> snapshot apply: fix region pending apply processing

tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/pd_task_handler.go, tikv/raftstore/peer.go, tikv/raftstore/peer_state.go, tikv/raftstore/peer_storage.go, tikv/raftstore/resolver.go, tikv/raftstore/server.go, tikv/raftstore/snapRunner.go, tikv/raftstore/ticker.go, tikv/raftstore/worker.go, tikv/raftstore/worker_test.go
- extract GlobalContext for immutable singletons.
- Separate RaftContext and StoreContext.
- Make names more consistent with their behaviors.
=> refactor raftstore

tikv/raftstore/restore.go, unistore-server/main.go
Fixes https://github.com/ngaut/unistore/issues/277
When unistore is killed soon after started, there is not lockstore dump file, we still need to restore the lockStore from 0 offset.
=> fix restore lockstore

tikv/raftstore/raft_client.go, unistore-server/main.go
Solving issue #287 
Reduce the server closing stream connection times and related error logs printing, make the raft client connection keepalive take effect
=> [RPC] Add keepalive for stream connection

tikv/cop_handler_test.go, tikv/mvcc.go, tikv/mvcc_test.go
- Add check for prewrite TTL for pessimistic transactions like tikv
- Refactor some test utilities, increase the `raftstore` coverage(11% -> 27%)
=> [txn] Add check for prewrite ttl for pessimistic txn

go.mod, go.sum, lockstore/lockstore.go, tikv/errors.go, tikv/mvcc.go, tikv/mvcc_test.go, tikv/server.go
1. Let the `minCommitTs` fields take effect for prewrite and commit
2. Complete the `CheckTxnStatus` API related logic, add `Action` and `RollbackIfNotExists` field, port some tests from tikv
coverage(tikv 21.9 -> 23.8)
=> [txn] Complete CheckTxnStatus related logic, and port tests

tikv/raftstore/applier.go, tikv/raftstore/peer.go
Issue #297  
Need to update the lockStore when rollbacking pessimistic locks
Jepsen test command
```
lein run test --workload=bank-multitable --read-lock=update --time-limit 120 --concurrency 2n --txn-mode "pessimistic"
```
Master branch jepsen test
```
wc -l history.txt 
600 history.txt
grep -P ":ok.*transfer" history.edn  | wc -l
3
```
Running jepsen test with this diff
```
wc -l history.txt 
3410 history.txt
grep -P ":ok.*transfer" history.edn  | wc -l
642
```
=> [txn]Do update the lockstore when rollbacking pessimistic lock

tikv/dbreader/db_reader.go, tikv/mvcc.go, tikv/mvcc/mvcc.go, tikv/mvcc/tikv.go, tikv/mvcc_test.go, tikv/server.go
Support `MvccGetByKey`  command, add this rpc handler
```
create table t1(c1 int primary key, c2 int);
insert into t1 values(1,1);
update t1 set c2 = c2 + 1 where c1 = 1;
update t1 set c2 = c2 + 50 where c1 = 1;
curl http://127.0.0.1:10080/mvcc/key/test/t1/1
{
"key": "74800000000000002B5F728000000000000001",
"region_id": 8,
"value": {
"info": {
"writes": [
{
"start_ts": 412951232233078785,
"commit_ts": 412951232233078786,
"short_value": "CAQIaA=="
},
{
"start_ts": 412951231617302529,
"commit_ts": 412951231630147585,
"short_value": "CAQIBA=="
},
{
"start_ts": 412951231053692929,
"commit_ts": 412951231053692930,
"short_value": "CAQIAg=="
}
],
"values": [
{
"start_ts": 412951232233078785,
"value": "CAQIaA=="
},
{
"start_ts": 412951231617302529,
"value": "CAQIBA=="
},
{
"start_ts": …
```
=> [storage] support mvcc get by key

tikv/dbreader/db_reader.go, tikv/mvcc.go, tikv/mvcc/mvcc.go, tikv/mvcc_test.go, tikv/raftstore/applier.go, tikv/raftstore/db_writer.go, tikv/write.go
Fixes https://github.com/ngaut/unistore/issues/264
By store Op_Lock directly to old key, we can ensure the latest keys are all valid and preserve transaction status
=> fix commit Op_Lock primary key lost transaction status

tikv/dbreader/db_reader.go, tikv/mvcc.go, tikv/mvcc/mvcc.go, tikv/mvcc_test.go, tikv/server.go
Support mvcc get ts read for debugging usage
```
curl http://127.0.0.1:10080/mvcc/txn/405179368526053377/test/t1
```
Returns the transaction commits/rollbacks up to the input startTs
=> [storage] Support get mvcc by ts

tikv/mvcc/tikv.go, tikv/mvcc_test.go, tikv/raftstore/applier.go, tikv/raftstore/db_writer.go, tikv/raftstore/restore.go
Change store to raft writer in `mvcc test`, fix two found problems
1. The applier command ops should follow input orders
eg:
```
(1) pessimistic lock one key using forUpdateTs1
(2) pessimistic the same lock using forUpdateTs2
```
Here the override (2) operation will add one `rollback` and one `put`,   but the applier did the `prewrite(the put)` first and then the `rollback(the rollback)`, this lock will be deleted unintended
2. The `minCommitTs` is not encoded into `put operation`, so after decoding, the value is incorrect
The current `make test` all passed, maybe we need to port more cases to solid the basic path
=> Change test store to raft writer, fix found problems

tikv/closure_exec.go, tikv/cop_handler_test.go
When dag executor is TableScan->Selection->Limit, the selection is not evaluated.
=> fix closure executor bug

tikv/errors.go, tikv/mvcc.go, tikv/mvcc_test.go, tikv/server.go
1. Make cleanup compatible, do check the lock TTL
2. Report error if committing pessimistic locks
3. Report error if pessimistic lock on rollbacked entry
4. Port txn tests(Pessimistic related)(
tikv package coverage 22.1% ->  28.3%
mvcc.go  52% -> 72%, currently most mvcc txn related interfaces are recorded)
Incompatibilities with tikv
1. Unistore will not collapse rollback record
2. Unistore pessimistic rollback will not be recorded, so the earlier raised pessimistic lock will succeed if arriving later than rollback operation
=> make kv cleanup compatible and do check the lock ttl

tikv/raftstore/restore.go, tikv/raftstore/restore_test.go
The pessimistic lock rollback should use the key from `delLock` field, or the restart of unistore may panic
like
```
goroutine 1 [running]:
github.com/ngaut/unistore/tikv/raftstore.restoreRollback(0x0, 0x0, 0xc04d54dbd0, 0xc0001516e0)
/home/rwork/go/src/unistore/tikv/raftstore/restore.go:105 +0x37
github.com/ngaut/unistore/tikv/raftstore.restoreAppliedEntry(0xc0001376e0, 0xc0004302d0, 0xc000151680, 0xc0001516e0, 0x0, 0x0)
/home/rwork/go/src/unistore/tikv/raftstore/restore.go:81 +0x18e
github.com/ngaut/unistore/tikv/raftstore.RestoreLockStore.func1(0xc0001961b0, 0x1b, 0x26, 0xc04d4cc000, 0x95, 0x2788a, 0x0, 0x0, 0x0, 0x40, ...)
/home/rwork/go/src/unistore/tikv/raftstore/restore.go:43 +0x180
github.com/coocood/badger.(*DB).IterateVLog.func1(0xc0001961b0, 0x1b, 0x26, 0xc04d4cc000, 0x95, …
```
=> add logic for pessimistic lock rollback restore

config/config.go
If the default value of split keys is not set, batch split would fail.
=> set default split keys

go.sum, lockstore/load_dump.go, lockstore/lockstore.go, lockstore/lockstore_test.go, tikv/cop_handler_test.go, tikv/raftstore/engine.go, tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/restore.go, tikv/raftstore/snap.go, tikv/raftstore/snap_test.go, tikv/raftstore/worker.go, tikv/write.go, unistore-server/main.go
So we don’t need to call Delete and Insert when update an entry.
=> lockstore supports Put operation

config/config-template.toml, config/config.go, tikv/mvcc.go, unistore-server/main.go
1. Add lock wait timeout config, and change the default max value to `1000ms` as the latest `tikv` refactor, and tested with `tidb` repo session tests `pessimistic suite`
2. Support config check command
=> support config check, add pessimistic lock wait timeout config

config/config.go, go.sum, tikv/mvcc.go, tikv/mvcc/db_writer.go, tikv/raftstore/applier.go, tikv/raftstore/db_writer.go, tikv/raftstore/db_writer_test.go, tikv/raftstore/engine.go, tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/msg.go, tikv/raftstore/pd_task_handler.go, tikv/raftstore/peer.go, tikv/raftstore/peer_storage.go, tikv/raftstore/peer_test.go, tikv/raftstore/raftlog/custom.go, tikv/raftstore/raftlog/raftlog.go, tikv/raftstore/raftlog/request.go, tikv/raftstore/raftstore_router.go, tikv/raftstore/restore_test.go, tikv/raftstore/router.go, tikv/raftstore/util.go, tikv/write.go
The custom raft log format is optional, we can still build TiKV compatible raft log.
After this optimization, the batch insert performance is doubled, exceeds the latest tikv.
Tested on a 40 core linux server
```
create table t (id bigint primary key auto_increment, c bigint)
```
Then run 8 workers do
```
for {
insert t (c) values ... // 500 rows
}
```
TiKV:
```
177000
185500
184500
178500
179000
181000
176000
182500
179500
177000
178000
178500
173500
177000
183000
176000
177500
179000
178500
185000
184000
183500
```
Unistore:
```
255000
227000
227000
233500
234500
255500
247000
209000
252500
257000
254500
256500
214500
264500
243000
256000
257500
```
=> support custom raft log to boost batch insert performance

lockstore/lockstore.go, lockstore/lockstore_test.go, tikv/mvcc.go, tikv/raftstore/applier.go, tikv/raftstore/engine.go, tikv/write.go
The sequential batch insert performance increased by about 50%
```
358600
376400
369000
287200
379800
377200
358200
309200
367400
377000
315600
370000
384600
374000
288400
382400
397800
365200
305800
382000
```
=> lockstore support PutWithHint and DeleleWithHint

config/config-template.toml, config/config.go, tikv/server.go, util/lockwaiter/lockwaiter.go, util/lockwaiter/lockwaiter_test.go
Add wakeup delay duration config,  wakeup the oldest lock waiter first
1. Make the lock wait wakeup ordering by txn startTs as many as possible
2. Optimize hot-update perfomance on single row
sysbench oltp_hot_update 512 thread on single row `update wm set v = v + 1 where id = 1`
master
```
SQL statistics:
queries performed:
read:                            0
write:                           47942
other:                           95884
total:                           143826
transactions:                        47942  (395.09 per sec.)
queries:                             143826 (1185.26 per sec.)
ignored errors:                      0      (0.00 per sec.)
reconnects:                          0      (0.00 per sec.)
General statistics:
total time:                          121.3436s
total …
```
=> add wake up delay duration, optimize wake up

tikv/cop_handler_test.go, tikv/mvcc_test.go, tikv/region.go, tikv/util.go
Change latch map to `sync.Map`, remove the latch mutex
Some bench under `master` and `dev`(without wakeup delay duration change)
Acquire latch cost reduces
Some bench on latch aquire and release will be done later in this post
```
master
SQL statistics:
queries performed:
read:                            0
write:                           46940
other:                           93880
total:                           140820
transactions:                        46940  (387.07 per sec.)
queries:                             140820 (1161.20 per sec.)
ignored errors:                      0      (0.00 per sec.)
reconnects:                          0      (0.00 per sec.)
General statistics:
total time:                          121.2696s
total number of events:              46940
Latency (ms):
min: …
```
=> refactor latch new implementation

tikv/errors.go, tikv/mvcc.go, tikv/server.go
The lock error should return lock type,  otherwise `tidb` lock resolver will get into dead loop keep reporting `txn not found`
`tps` in sysbench tests sometimes  will get into 0 and last for 20s(default lock TTL), because of the missing lock type like `pessimistic lock`
=> server: return lock type when error locked

tikv/mvcc.go, tikv/mvcc_test.go, tikv/raftstore/applier.go
Issue #328 
Do not let `tidb` report partial commit error log during benchmark tests
=> txn: check key commited from store if lock not found

tikv/raftstore/engine.go
When we restore lockStore from raft log, it’s normal that the DeleteLock deleting a non-exist key.
=> fix panic when restore lockStore data from raft log.

tikv/raftstore/applier.go, tikv/raftstore/engine.go, tikv/raftstore/peer.go, tikv/raftstore/peer_storage.go, tikv/write.go
Some transaction in raftstore code is never discarded
- discard the transactions.
- simplify the ReadExecutor because the snapshot it's never used.
=> fix memory leak

tikv/mvcc.go, util/lockwaiter/lockwaiter.go
If 'ReturnValues' is true, we should not sort the mutations.
=> fix pessimistic lock return values

tikv/raftstore/fsm_peer.go, tikv/raftstore/fsm_store.go, tikv/raftstore/peer_worker.go, tikv/raftstore/ticker.go
raftWorker sends message to tickDriver and tickDriver sends message to raftWorker.
When raftWorker channel is full, the server blocking forever.
=> fix raft store blocking on tickDriver due to channel is full

tikv/mvcc.go, tikv/mvcc_test.go, tikv/server.go, unistore-server/main.go
BatchGet should keep getting all the keys even if there are locked keys.
=> fix BatchGet return early when meet lock

config/config.go, go.mod, go.sum, tikv/dbreader/db_reader.go, tikv/mvcc.go, tikv/mvcc/db_writer.go, tikv/mvcc/mvcc.go, tikv/mvcc_test.go, tikv/raftstore/applier.go, tikv/raftstore/bootstrap.go, tikv/raftstore/db_writer.go, tikv/raftstore/engine.go, tikv/raftstore/fsm_store.go, tikv/raftstore/peer_storage.go, tikv/raftstore/raftlog/custom.go, tikv/raftstore/restore.go, tikv/raftstore/restore_test.go, tikv/raftstore/snap.go, tikv/raftstore/snap_applier.go, tikv/raftstore/snap_builder.go, tikv/raftstore/snap_test.go, tikv/raftstore/test_util_test.go, tikv/raftstore/worker.go, tikv/raftstore/worker_test.go, tikv/server.go, tikv/util.go, tikv/write.go, unistore-server/main.go
- eliminate the extra write cost caused by move old version data to another key.
- Simplify the older version data management logic.
=> replace badger version with transaction TS.

tikv/cop_handler_test.go, tikv/mvcc.go, tikv/mvcc_test.go, tikv/raftstore/applier.go, tikv/raftstore/db_writer.go, tikv/server.go
- CustomLog rollback deletes a UserKey should not trim last 8 bytes.
- ScanLock should respect the limit parameter.
- ResolveLock can take given keys to avoid Scan.
- Modify the test to use CustomLog to cover the case.
=> fix Rollback doesn’t delete the lock

tikv/analyze.go
A multi-column index should insert on every prefix of row values instead of full index.
=> fix analyze CMSketch

pd/client.go, tikv/mvcc/db_writer.go, tikv/raftstore/engine.go, unistore-server/main.go
When using managed DB, we write apply state key the same version many times, it is possible that an old value is returned because it has the same version.
The solution is that we get a TS from PD at start time, put it in DBBundle, when writing to KV DB, modify the version if its version is 1.
=> fix apply state read stale value

tikv/mvcc_test.go, tikv/region.go, tikv/server.go
Fixes https://github.com/ngaut/unistore/issues/368
So we don’t need to maintain refCount and wait for the parent region to finish.
=> use global latch instead of one in a region

tikv/mvcc.go, tikv/raftstore/peer_storage.go
When blob is enabled, the Value returns a reference to a cache memory, that cache can be rewritten on the next Value call.
=> fix bug caused by item.Value without copy

go.mod, go.sum, tikv/raftstore/bootstrap.go, tikv/raftstore/peer_storage.go, tikv/raftstore/snap_test.go
Fixes https://github.com/ngaut/unistore/issues/377
The KvTS is not rewritten to DBBundle.StateTS if we use DB.Update directly,
So Delete does not take effect, then another restart will see prepareBootstrapKey,
And then delete the first region.
=> fix bootstrap failed to delete prepareBootstrapKey

go.mod, go.sum, tikv/mvcc_test.go
Fixes https://github.com/ngaut/unistore/issues/383
1 table with 10million rows of sysbench table.
After 10 minutes of update-non-index, the count time reduced from 2s to 1.1s。
=> update badger to skip old version and fix test

lockstore/lockstore.go
Just like https://github.com/pingcap/tidb/pull/14972
=> lockstore: compatible with Go 1.14's checkptr

tikv/server.go
These two handlers don't acquire server ref count and check `closed` flag.
This will cause panic like https://github.com/pingcap/tidb/issues/18236
=> tikv: add server closed check in SplitRegion and KvGC

go.mod, go.sum, tikv/errors.go, tikv/mvcc.go, tikv/mvcc/mvcc.go, tikv/mvcc_test.go, tikv/server.go
Try to implement these async commit protocol related features:
- Update `kvproto`.
- Return `minCommitTS` in `Prewrite` response, fetching new ts from PD.
- `CheckTxnStatus` related change.
- Return `minCommitTS` in lock error information.
Tests:
- Unit tests.
- Simple demo with TiDB changes using async commit protocol.
=> txn: implement some async commit related logic

tikv/mvcc.go
The input `key` of `checkLock` is a temporary buffer of the lock iterator, we should copy it to build lock error.
=> safe copy lock key when build lock error

util/lockwaiter/lockwaiter.go
Try to fix the issue https://github.com/pingcap/tidb/issues/19868, remove the `LockTS` set for wake up.
=> remove the lock ts set for waiter wakeup to avoid race

tikv/mvcc.go
Port https://github.com/tikv/tikv/pull/8598
This change guarantees that a point get can read the record which has just been written using async commit.
=> do not allow primary get to bypass async commit locks

tikv/errors.go, tikv/mvcc.go, tikv/server.go
CheckTxnStatus is changed to be aligned with TiKV.
I've tested locally that with this fix, the tests in https://github.com/pingcap/tidb/pull/20073 can pass.
=> Fix missing lock fields in KeyError and forbid CheckTxnStatus pushing async commit locks

tikv/server.go
Everytime the mpp execution of a task ends, the handler should be cleaned.
=> clean task hander after execution

go.mod1, go.sum1, tikv/server.go
This PR is going to update kvproto to the latest version. Currently, it blocks the TiDB to use the latest kvproto.
=> *: update kvproto to the latest version

tikv/server.go
the finish of reqCtx will close the reader thoroughly. So we have to finish it after the execution ends.
=> adjust the position of finish req ctx in mpp request

tikv/server.go
transfer `ctx` to unistore when executing MPP.
work with https://github.com/pingcap/tidb/pull/23056.
=> add ctx into mppctx

sdb/split.go, tikv/raftstore/peer.go, tikv/raftstore/raftlog/custom.go
If a shard has entered pre-split state, reject any future compaction.
Fixes #456
=> fix the bug compaction conflicts with split.

sdb/shard.go, sdb/split.go, sdb/table/sstable/table.go
If we detect a sequential write pattern by the mem-table, we choose the second latest mem-table's biggest key as the split key, then we only need to split one L1 file.
Fixes https://github.com/ngaut/unistore/issues/486
=> optimize sequential write

sdb/compaction.go
pre-split flush should be executed later than pre-split, or pre-split would fail.
=> wait for shard pre-split before apply pre-split flush

engine/engine.go, engine/shard.go, engine/table/sstable/table.go, tikv/raftstore/peer.go
* Use l0 key as the split key when the l0 tables size is larger than 30%.
* Fix bug where recovery state could not continue to split.
=> use l0 key as the split key when the l0 tables size is larger than 30%

engine/compaction.go, engine/engine.go, engine/fileutil/preallocate_linux.go, engine/fileutil/preallocate_others.go, engine/fileutil/sync.go, engine/fileutil/sync_darwin.go, engine/fileutil/sync_linux.go, engine/split.go, tikv/raftstore/worker.go
This panic bug was found in 4 nodes deployment. So peer may be removed due to region balance.
=> fix panic by check if shard is nil

engine/compaction.go, engine/engine.go, engine/shard.go, engine/split.go, engine/write.go
The current calculation method may have duplicate memory table timestamps. 
This PR fixes this bug.
=> calculate memory table timestamp using raft log index instead of meta sequence

config/config.go, tikv/raftstore/fsm_peer.go, tikv/raftstore/peer_worker.go
Before:
```
for each region {
handleMsgs
}
for each region {
newReady
}
for each region {
handleReady
}
for each region {
scheduleApply
}
```
After:
```
for each region {
handleMsgs
newReady
handleReady
scheduleApply
}
```
The apply worker can handle the task earlier, so the latency would be lower.
Since the apply task can be evenly spread within a period of time, the CPU utilization would be more stable.
=> refactor raft worker process for lower latency

config/config.go, tikv/raftstore/config.go, tikv/raftstore/peer_worker.go
So the follower response raft message can be sent sooner.
=> limit the max batch size of a raft worker

engine/dfs/builtindfs/builtindfs.go, tikv/server.go
The BuiltinDFS utilize the local storage to implement the DFS interface.
So we can deploy on private environments without S3 service.
=> implement BuiltinDFS
